//
//  Z3MapView.h
//  OutWork
//
//  Created by 童万华 on 2019/7/13.
//  Copyright © 2019 ZZHT. All rights reserved.
//

#import <Foundation/Foundation.h>

extern NSNotificationName const Z3MapViewRequestFormNotification;
extern NSNotificationName const Z3MapViewRequestDetailNotification;
extern NSString * const Z3MapViewRequestFormUserInfoKey;
extern NSString * const Z3MapViewRequestDetailUserInfoKey;

//组合条件查询相关的通知
extern NSNotificationName const Z3MapViewIdentityFeaturesInGlobalNotification;
extern NSNotificationName const Z3MapViewIdentityFeaturesInVisibleNotification;
extern NSNotificationName const Z3MapViewIdentityFeaturesByMakeRectNotification;
extern NSNotificationName const Z3MapViewIdentityFeaturesByMakeRectComplicationNotification;
extern NSNotificationName const Z3MapViewIdentityFeaturesComplicationNotification;
extern NSNotificationName const Z3MapViewCancelIdentityFeaturesNotification;
extern NSNotificationName const Z3HUDIdentityResultDiplayViewDidChangeSelectIndexNotification;
extern NSNotificationName const Z3MapViewIdentityContextDidChangeSelectIndexNotification;
extern NSNotificationName const Z3MapViewIdentityContextDeselectIndexNotification;

//图层控制相关的通知
extern NSNotificationName const MasterViewControllerShowDetailViewNotification;
extern NSNotificationName const ZZCommonMapViewControllerShowLayerFilterViewNotification;
extern NSNotificationName const Z3MapViewLayerFilterViewControllerSelectIndexNotification;
extern NSNotificationName const Z3MapViewLayerFilterViewControllerDeselectIndexNotification;

//爆管分析页面数据通信
extern NSNotificationName const Z3PipeLeakAnalysisViewControllerQueryLeakPipeNotification;
extern NSNotificationName const Z3PipeLeakAnalysisViewControllerQueryValueNotification;
extern NSNotificationName const Z3PipeLeakAnalysisViewControllerClearNotification;
//爆管分析查看详情页
extern NSNotificationName const Z3HUDPipeLeakCalloutViewQuickLookDetailNotification;
//已选中爆管点
extern NSNotificationName const Z3MapViewQueryLeakPipeXtdSelectedIssueLocationNotification;
//已取消选中爆管点
extern NSNotificationName const Z3MapViewQueryLeakPipeXtdDeselectIssueLocationNotification;
extern NSString * const Z3MapViewOnlineFeatureLayerNameKey;


