//
//  Z3MapView.h
//  OutWork
//
//  Created by 童万华 on 2019/7/13.
//  Copyright © 2019 ZZHT. All rights reserved.
//

#import <Foundation/Foundation.h>

extern NSNotificationName const Z3MapViewRequestFormNotification;
extern NSNotificationName const Z3MapViewRequestDetailNotification;
extern NSString * const Z3MapViewRequestFormUserInfoKey;
extern NSString * const Z3MapViewRequestDetailUserInfoKey;

//组合条件查询相关的通知
extern NSNotificationName const Z3MapViewIdentityFeaturesInGlobalNotification;
extern NSNotificationName const Z3MapViewIdentityFeaturesInVisibleNotification;
extern NSNotificationName const Z3MapViewIdentityFeaturesByMakeRectNotification;
extern NSNotificationName const Z3MapViewIdentityFeaturesByMakeRectComplicationNotification;
extern NSNotificationName const Z3MapViewIdentityFeaturesComplicationNotification;
extern NSNotificationName const Z3MapViewCancelIdentityFeaturesNotification;
extern NSNotificationName const Z3HUDIdentityResultDiplayViewDidChangeSelectIndexNotification;
extern NSNotificationName const Z3MapViewIdentityContextDidChangeSelectIndexNotification;
extern NSNotificationName const Z3MapViewIdentityContextDeselectIndexNotification;

//图层控制相关的通知
extern NSNotificationName const MasterViewControllerShowDetailViewNotification;
extern NSNotificationName const ZZCommonMapViewControllerShowLayerFilterViewNotification;
extern NSNotificationName const Z3MapViewLayerFilterViewControllerSelectIndexNotification;
extern NSNotificationName const Z3MapViewLayerFilterViewControllerDeselectIndexNotification;

//点击查询
extern NSNotificationName const Z3MapViewTapQueryXtdIdentitySuccessNotification;
extern NSNotificationName const Z3MapViewTapQueryXtdIdentityGraphicFailureNotification;
extern NSNotificationName const Z3TapIdentityResultViewControllerDoneNotification;
extern NSNotificationName const Z3TapIdentityResultViewControllerCancelNotification;

//爆管分析页面数据通信
//爆管分析-点击爆管点
extern NSNotificationName const Z3PipeLeakAnalysisViewControllerQueryLeakPipeNotification;
//爆管分析-点击关阀搜索
extern NSNotificationName const Z3PipeLeakAnalysisViewControllerQueryValueNotification;
//爆管分析-点击清除
extern NSNotificationName const Z3PipeLeakAnalysisViewControllerClearNotification;
//爆管分析查看详情页
extern NSNotificationName const Z3HUDPipeLeakCalloutViewQuickLookDetailNotification;
//分析爆管点成功
extern NSNotificationName const Z3MapViewQueryLeakPipeXtdAnaylseSuccessNotification;
//已选中爆管点
extern NSNotificationName const Z3MapViewQueryLeakPipeXtdSelectedIssueLocationNotification;
//已取消选中爆管点
extern NSNotificationName const Z3MapViewQueryLeakPipeXtdDeselectIssueLocationNotification;
//二次关阀
extern NSNotificationName const Z3HUDPipeLeakCalloutViewCloseValveNotification;

//问题反馈
extern NSNotificationName const Z3DevicePickerViewCellTapForSelectDeviceNotification;
extern NSNotificationName const Z3LocationChoiceCellTapForLocationDeviceNotification;
extern NSNotificationName const Z3IssueFeedbackViewControllerClearMapViewNotification;
extern NSString * const Z3MapViewOnlineFeatureLayerNameKey;


